//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::manufacturer::Entity as Manufacturer;
pub use super::rating_axis::Entity as RatingAxis;
pub use super::review::Entity as Review;
pub use super::review_rating::Entity as ReviewRating;
pub use super::sauce::Entity as Sauce;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::user::Entity as User;
pub use super::user_google_login::Entity as UserGoogleLogin;
