//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "rating_axis")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub rating_axis_id: i32,
    pub rating_axis_name: String,
    pub min_value_desc: String,
    pub max_value_desc: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::review_rating::Entity")]
    ReviewRating,
}

impl Related<super::review_rating::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewRating.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
