//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sauce")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sauce_id: i32,
    pub sauce_name: String,
    pub manufacturer_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::manufacturer::Entity",
        from = "Column::ManufacturerId",
        to = "super::manufacturer::Column::ManufacturerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Manufacturer,
}

impl Related<super::manufacturer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Manufacturer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
